### ISSUE TITLE
滴水效果

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/icss#4]
[单标签实现滴水效果](https://csscoco.com/inspiration/#/./filter/filter-single-div-water-drop?id=%e5%8d%95%e6%a0%87%e7%ad%be%e5%ae%9e%e7%8e%b0%e6%bb%b4%e6%b0%b4%e6%95%88%e6%9e%9c)

``` scss
html,
body {
    width: 100%;
    height: 100%;
    overflow: hidden;
    background: #000;
    filter: blur(3px) contrast(10);
}

div {
    position: relative;
    width: 640px;
    height: 106px;
    color: #fff;
    font-size: 124px;
    text-align: center;
    margin: 100px auto;
    border-bottom: 10px solid #fff;
    transform: skewY(5deg);
    
    &::before,
    &::after {
        position: absolute;
        content: "";
        bottom : -20px;
        left: 0;
        width: 10px;
        height: 20px;
        border-radius: 50%;
        background: #fff;
        transform: translate(0, 0);
        animation: move 7.5s ease-in-out infinite;
    }
    
    &::after {
        animation: move 7.5s ease-in-out 1s infinite;
    }
}

@keyframes move {
    80% {        
        bottom : -30px;
        transform: translate(623px, 0);
    } 93% {
        transform: translate(623px, 3px);
        opacity: 1;
    }100% {
        transform: translate(623px, 150px);
        opacity: 0;
    }
}
```

``` html
<div>MAGICCSS</div>
```
