### ISSUE TITLE
流光文字效果

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/icss#5]
[background-clip 实现流光文字效果](https://csscoco.com/inspiration/#/./background/bg-clip-text-shine?id=background-clip-%e5%ae%9e%e7%8e%b0%e6%b5%81%e5%85%89%e6%96%87%e5%ad%97%e6%95%88%e6%9e%9c)

``` scss
@import url('https://fonts.googleapis.com/css2?family=Krona+One&display=swap');

html, body {
    width: 100%;
    height: 100%;
    background-image: radial-gradient(ellipse farthest-side at 40% 0%, #455A64 0%, #263238 60%, #1a2327 100%);
    display: flex;
    font-family: 'Krona One', sans-serif;
}

p {
    position: relative;
    margin: auto;
    font-size: 5rem;
    word-spacing: 0.2em;
    display: inline-block;
    line-height: 1;
    white-space: nowrap;
    color: transparent;
    background-color: #E8A95B;
    background-clip: text;
}

p::after {
    content: attr(data-text);
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: 5;
    background-image: linear-gradient(120deg, transparent 0%, transparent 6rem, white 11rem, transparent 11.15rem, transparent 15rem, rgba(255, 255, 255, 0.3) 20rem, transparent 25rem, transparent 27rem, rgba(255, 255, 255, 0.6) 32rem, white 33rem, rgba(255, 255, 255, 0.3) 33.15rem, transparent 38rem, transparent 40rem, rgba(255, 255, 255, 0.3) 45rem, transparent 50rem, transparent 100%);
    background-clip: text;
    background-size: 150% 100%;
    background-repeat: no-repeat;
    animation: shine 5s infinite linear;
}

@keyframes shine {
  0% {
    background-position: 50% 0;
  }
  100% {
    background-position: -190% 0;
  }
}
```

``` html
<p data-text="Lorem ipsum dolor"> Lorem ipsum dolor </p>
```
