### ISSUE TITLE
实现图片变幻

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/icss#6]
[mask-image 实现图片变幻](https://csscoco.com/inspiration/#/./background/bg-mask-image?id=mask-image-%e5%ae%9e%e7%8e%b0%e5%9b%be%e7%89%87%e5%8f%98%e5%b9%bb)

``` scss
$img2: 'https://picsum.photos/id/10/1920/1080';

$img1: 'https://picsum.photos/id/20/1920/1080';

$count: 360;

div {
    position: absolute;
    top:0;
    left: 0;
    width: 100vw;
    height: 100vh;
    
}

.a {
    background: url($img1);
    background-size: cover;
}

.b {
    background: url($img2);
    background-size: cover;
    mask-image: linear-gradient(0, rgba(0, 0, 0, 1) 40%, transparent 60%);
    mask-image-position: 50% 50%;
    animation: move 10s infinite;
}

@keyframes move {
    
    @for $i from 0 through $count {
        #{$i / $count * 100}% {
            mask-image: linear-gradient($i / $count * 360deg, rgba(0, 0, 0, 1) 40%, transparent 60%);
        }        
    }
}
```

``` html
<div class="a"></div>
<div class="b"></div>
```
