### ISSUE TITLE
实现文字的渐现

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/icss#7]
[mask-image 实现文字的渐现](https://csscoco.com/inspiration/#/./background/bg-mask-text-show?id=mask-image-%e5%ae%9e%e7%8e%b0%e6%96%87%e5%ad%97%e7%9a%84%e6%b8%90%e7%8e%b0)

``` scss
@import url('https://fonts.googleapis.com/css2?family=Reggae+One&display=swap');

html, body {
    width: 100%;
    height: 100%;
    display: flex;
    background: #000;
}

p {
        margin: auto;
        font-family: 'Reggae One', cursive;
        font-size: 48px;
        color: #fff;
        mask: radial-gradient(circle at 0 50%, #000, transparent 10%, transparent 0);
        mask-size: 100%;
        animation: scale 5s infinite;
}

.radial {
    mask: radial-gradient(circle at 50% 0, #000, transparent 20%, transparent 0);
    mask-size: 100% 100%;
    animation: scale2 5s infinite;
}

@keyframes scale {
    0% {
        mask-size: 100%;
    }
    50%,
    100% {
        mask-size: 2000%;
    }
}

@keyframes scale2 {
    0% {
        mask-size: 100% 100%;
    }
    50%,
    100% {
        mask-size: 100% 2000%
    }
}
```

``` html
<p>Hello Mask</p>
<p class="radial">Hello Mask</p>
```
